# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RGgwxEWU8VEk_KLQFM_yesz8EFGsYbU
"""

def ustoz_ismlari(ustoz_ismi):
  if(ustoz_ismi=="Xalilov Durbek"):
    return "Sun'iy intellekt asoslari"
  elif ustoz_ismi=="Djalilov Mamatisa":
    return "Komyuterni tashkil etish"
  elif ustoz_ismi=="Xonto'rayev Sardor":
   return "Ma'lumotlar tuzilmasi va algoritmlar"
  elif ustoz_ismi=="Jo'rayeva Gulnozaxon":
    return "Elektronika va sxemalar"
  elif ustoz_ismi=="Turdimatov Ma'murjon":
   return "Kiberxavfsizlik asoslari"
  elif ustoz_ismi=="Raxmatov Rasuljon":
    return "Kiberxavfsizlik asoslari"
  elif ustoz_ismi=="Qadamova Zulayxo":
   return "Sun’iy intellekt asoslari"
  elif ustoz_ismi=="Qurbonova Gulruxsor":
    return "Komyuterni tashkil etish"
  elif ustoz_ismi=="Abdullayeva Mohigul":
   return "Ma'lumotlar tuzilmasi va algoritmlar"
  else:
   return "Bu ustoz bizga darsga kirmaydi "
ustoz_ism=input("Ustoz familyasi va ismini kiriting ")
natija=ustoz_ismlari(ustoz_ism)
print(natija)

